import { Teacher, Subject, Room, Class } from '../types';

export const mockTeachers: Teacher[] = [
  {
    id: 't1',
    teacherCode: 'GV001',
    username: 'nguyenvana',
    password: '123456',
    firstName: 'A',
    lastName: 'Nguyễn Văn',
    name: 'Nguyễn Văn A',
    phone: '0123456789',
    email: 'nguyenvana@nuce.edu.vn',
    address: 'Hà Nội',
    department: 'Khoa học máy tính',
    subjects: ['s1', 's2'],
  },
  {
    id: 't2',
    teacherCode: 'GV002',
    username: 'tranthib',
    password: '123456',
    firstName: 'B',
    lastName: 'Trần Thị',
    name: 'Trần Thị B',
    phone: '0123456790',
    email: 'tranthib@nuce.edu.vn',
    address: 'Hà Nội',
    department: 'Khoa học máy tính',
    subjects: ['s3', 's4'],
  },
  {
    id: 't3',
    teacherCode: 'GV003',
    username: 'levanc',
    password: '123456',
    firstName: 'C',
    lastName: 'Lê Văn',
    name: 'Lê Văn C',
    phone: '0123456791',
    email: 'levanc@nuce.edu.vn',
    address: 'Hà Nội',
    department: 'Khoa học máy tính',
    subjects: ['s5', 's6'],
  },
  {
    id: 't4',
    teacherCode: 'GV004',
    username: 'phamthid',
    password: '123456',
    firstName: 'D',
    lastName: 'Phạm Thị',
    name: 'Phạm Thị D',
    phone: '0123456792',
    email: 'phamthid@nuce.edu.vn',
    address: 'Hà Nội',
    department: 'Khoa học máy tính',
    subjects: ['s7', 's8'],
  },
  {
    id: 't5',
    teacherCode: 'GV005',
    username: 'hoangvane',
    password: '123456',
    firstName: 'E',
    lastName: 'Hoàng Văn',
    name: 'Hoàng Văn E',
    phone: '0123456793',
    email: 'hoangvane@nuce.edu.vn',
    address: 'Hà Nội',
    department: 'Khoa học máy tính',
    subjects: ['s1', 's3'],
  },
];

export const mockSubjects: Subject[] = [
  {
    id: 's1',
    name: 'Cấu trúc dữ liệu và giải thuật',
    code: 'CS101',
    credits: 4,
    department: 'Khoa học máy tính',
    requiredHours: 4,
  },
  {
    id: 's2',
    name: 'Lập trình hướng đối tượng',
    code: 'CS102',
    credits: 3,
    department: 'Khoa học máy tính',
    requiredHours: 3,
  },
  {
    id: 's3',
    name: 'Cơ sở dữ liệu',
    code: 'CS201',
    credits: 4,
    department: 'Khoa học máy tính',
    requiredHours: 4,
  },
  {
    id: 's4',
    name: 'Mạng máy tính',
    code: 'CS202',
    credits: 3,
    department: 'Khoa học máy tính',
    requiredHours: 3,
  },
  {
    id: 's5',
    name: 'Trí tuệ nhân tạo',
    code: 'CS301',
    credits: 4,
    department: 'Khoa học máy tính',
    requiredHours: 4,
  },
  {
    id: 's6',
    name: 'Học máy',
    code: 'CS302',
    credits: 3,
    department: 'Khoa học máy tính',
    requiredHours: 3,
  },
  {
    id: 's7',
    name: 'An toàn thông tin',
    code: 'CS401',
    credits: 3,
    department: 'Khoa học máy tính',
    requiredHours: 3,
  },
  {
    id: 's8',
    name: 'Phát triển ứng dụng web',
    code: 'CS402',
    credits: 4,
    department: 'Khoa học máy tính',
    requiredHours: 4,
  },
];

export const mockRooms: Room[] = [
  {
    id: 'r1',
    name: 'A101',
    capacity: 60,
    type: 'theory',
  },
  {
    id: 'r2',
    name: 'A102',
    capacity: 60,
    type: 'theory',
  },
  {
    id: 'r3',
    name: 'B201',
    capacity: 40,
    type: 'lab',
  },
  {
    id: 'r4',
    name: 'B202',
    capacity: 40,
    type: 'lab',
  },
  {
    id: 'r5',
    name: 'C301',
    capacity: 80,
    type: 'both',
  },
  {
    id: 'r6',
    name: 'C302',
    capacity: 80,
    type: 'both',
  },
];

export const mockClasses: Class[] = [
  {
    id: 'c1',
    name: 'CS101-01',
    subjectId: 's1',
    teacherId: 't1',
    numberOfStudents: 55,
    sessionsPerWeek: 2,
  },
  {
    id: 'c2',
    name: 'CS102-01',
    subjectId: 's2',
    teacherId: 't1',
    numberOfStudents: 45,
    sessionsPerWeek: 2,
  },
  {
    id: 'c3',
    name: 'CS201-01',
    subjectId: 's3',
    teacherId: 't2',
    numberOfStudents: 50,
    sessionsPerWeek: 2,
  },
  {
    id: 'c4',
    name: 'CS202-01',
    subjectId: 's4',
    teacherId: 't2',
    numberOfStudents: 40,
    sessionsPerWeek: 2,
  },
  {
    id: 'c5',
    name: 'CS301-01',
    subjectId: 's5',
    teacherId: 't3',
    numberOfStudents: 35,
    sessionsPerWeek: 2,
  },
  {
    id: 'c6',
    name: 'CS302-01',
    subjectId: 's6',
    teacherId: 't3',
    numberOfStudents: 38,
    sessionsPerWeek: 2,
  },
  {
    id: 'c7',
    name: 'CS401-01',
    subjectId: 's7',
    teacherId: 't4',
    numberOfStudents: 42,
    sessionsPerWeek: 2,
  },
  {
    id: 'c8',
    name: 'CS402-01',
    subjectId: 's8',
    teacherId: 't4',
    numberOfStudents: 48,
    sessionsPerWeek: 2,
  },
];
